# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  database: ajaxsubmit_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ajaxsubmit_test
  username: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: glzretnzii
  host: ec2-50-19-225-156.compute-1.amazonaws.com
  username: glzretnzii
  password: SknY8yZ-vvf3HJK_RIUc
  pool: 5
  timeout: 5000

